# Generated by Django 4.1.3 on 2023-01-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_profilemanager_alter_answer_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tags',
        ),
    ]
