# Generated by Django 4.1.3 on 2023-01-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_answer_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
