# Generated by Django 4.1.3 on 2023-01-23 19:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_answer_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='liketoquestion',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
