# Generated by Django 4.1.3 on 2023-01-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_liketoquestion_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='anonymous_avatar.png', upload_to='avatars'),
        ),
    ]
